version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Express backend serving static files
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
      - PORT=5000
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
