version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # React frontend
    volumes:
      # Mount the source code for hot reloading
      - ./app/src:/app/src
      - ./app/public:/app/public
      # Mount these files individually so they can be modified without rebuilding
      - ./app/package.json:/app/package.json
      - ./app/package-lock.json:/app/package-lock.json
      - ./app/tsconfig.json:/app/tsconfig.json
      - ./app/craco.config.js:/app/craco.config.js
      # Let container use its own node_modules to avoid permission issues
      # Exclude node_modules from host to prevent conflicts and reduce memory usage
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true  # Enable file watching in Docker on some systems
      - CHOKIDAR_USEPOLLING=true  # Enable polling for hot reload
      - NODE_OPTIONS=--max-old-space-size=2048  # Increased Node.js memory allocation
      - GENERATE_SOURCEMAP=false  # Disable source maps to save memory
      - DISABLE_ESLINT_PLUGIN=true  # Disable ESLint to save memory
      - FAST_REFRESH=true  # Enable React Fast Refresh
      - PORT=3000  # Frontend server port
      - NODE_ENV=development
      - TSC_COMPILE_ON_ERROR=true  # Allow TypeScript compilation to continue on errors
      - ESLINT_NO_DEV_ERRORS=true  # Don't fail on ESLint errors
      - SKIP_PREFLIGHT_CHECK=true  # Skip preflight checks
    deploy:
      resources:
        limits:
          memory: 4G  # Increased memory limit to prevent OOM kills
        reservations:
          memory: 1G  # Increased memory reservation
    tmpfs:
      - /app/node_modules/.cache  # Use tmpfs for cache to reduce memory pressure
    stdin_open: true  # Required for react-scripts start
    tty: true  # Required for react-scripts start
