version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      x-bake:
        platforms:
          - linux/amd64
        cache-from:
          - type=gha
        cache-to:
          - type=gha,mode=max
    ports:
      - "3000:3000"  # Express server serving React app
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=256
      - PORT=3000
    deploy:
      resources:
        limits:
          memory: 512M  # Reduced from 1G
        reservations:
          memory: 128M  # Minimal reservation
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "buildkit,builder"
